spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always  # Ensure database initialization on startup

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # Hibernate will attempt to update the schema

logging:
  level:
    org:
      hibernate:
        SQL: debug  # Enable Hibernate SQL logging for debugging purposes